language: csharp
solution: SimplCommerce.sln
sudo: required
dist: xenial
dotnet: 5.0.100
mono: none
os:
  - linux

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
  - dotnet restore

script:
  - dotnet build ./SimplCommerce.sln
  - ./run-tests.sh
