name: Express Store CI & CD

on:
  push:
    branches: [ dev-p1 ]
  pull_request:
    branches: [ master ]

jobs:
  build_NET5:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./SimplCommerce.sln
    - name: Build
      run: dotnet build ./SimplCommerce.sln
    - name: Test
      run: dotnet test ./SimplCommerce.sln
  build_NET6_Cms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./ExpressStoreCms.sln
    - name: Build
      run: dotnet build ./ExpressStoreCms.sln
    - name: Test
      run: dotnet test ./ExpressStoreCms.sln
  

